# Generated by Django 6.0.7 on 2026-07-12 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='nom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('adresse', models.TextField(blank=True, verbose_name='adresse')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('pays', models.CharField(blank=True, max_length=100, verbose_name='pays')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['nom'],
            },
        ),
    ]
