# Generated by Django 6.0.7 on 2026-07-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options_client_code_postal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.TextField(blank=True, default='', verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='client',
            name='code_postal',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='pays',
            field=models.CharField(blank=True, default='France', max_length=50, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ville',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ville'),
        ),
    ]
