# Generated by Django 6.0.7 on 2026-07-15 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_adresse_alter_client_code_postal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['owner', 'nom'], name='clients_cli_owner_i_d3c68e_idx'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('owner', 'email'), name='unique_client_email_per_owner'),
        ),
    ]
