# Generated by Django 6.0.7 on 2026-07-13 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        ('products', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Optionnel : associe cette ligne à un produit du catalogue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='products.product', verbose_name='produit'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='description',
            field=models.CharField(help_text='Pré-rempli depuis le produit sélectionné, modifiable librement.', max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, help_text='Pré-rempli depuis le produit sélectionné, modifiable librement.', max_digits=12, verbose_name='prix unitaire'),
        ),
    ]
