# Generated by Django 6.0.7 on 2026-07-13 09:55

import django.db.models.deletion
import facturation.products.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, help_text='Format recommandé : carré, 800x800px maximum.', null=True, upload_to=facturation.products.models.product_image_upload_path, verbose_name='image')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='prix unitaire')),
                ('gere_stock', models.BooleanField(default=False, help_text='Active le suivi de quantité disponible pour ce produit.', verbose_name='gérer le stock')),
                ('stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='stock disponible')),
                ('actif', models.BooleanField(default=True, help_text='Visible dans les listes de sélection.', verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ['nom'],
            },
        ),
    ]
